# Generated by Django 4.2.17 on 2026-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_telegrameditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawnews',
            name='rubric',
            field=models.CharField(choices=[('Политика', 'Политика'), ('Экономика', 'Экономика'), ('Происшествия', 'Происшествия'), ('Криминал', 'Криминал'), ('Право', 'Право'), ('Общество', 'Общество'), ('Мир', 'Мир'), ('Наука', 'Наука'), ('Здоровье', 'Здоровье'), ('Образование', 'Образование'), ('Культура', 'Культура'), ('Спорт', 'Спорт'), ('Технологии', 'Технологии'), ('Транспорт', 'Транспорт'), ('Экология', 'Экология'), ('Недвижимость', 'Недвижимость')], max_length=100),
        ),
    ]
